### ISSUE TITLE
Customizations for Multi Slider

### ISSUE THREAD

**Issue by goonerDroid** [apptik/MultiSlider#1]
Hey first of all great libarary.Love your multiple thumbs widget.Great work.Would like to know if there is any way to increase the bar width size and also color it without using drawables.Thanks once again!!

**Comment by djodjoni** [comment]
Hey, thanks for the feedback!
Regarding changing the color you can always put a "color" resource instead of a drawable (if you want a simple color) in the "range"  and "track" arguments .
However this will fill in the whole space for the View wich will be basically as heigh as it is the thumb and i suppose this is not what you want.

I have planned to do min/max height for track and ranges and also a specific height for those, but it wont be ready soon.

However using drawables is quite easy. You can generate the defult one from here: http://android-holo-colors.com/
pickup ur you color and generate the seekBar resources then edit the .9.png to the height you want.

Anyway I will let you know when the new agrs are in place.

Cheers,
jj

**Comment by goonerDroid** [comment]
Thanks the reason i wanted Color params is that i dont want to the hassle of creating the drawables.Although i have started working on the customizations i would let you know when i am done with it so that you can merge.Also just ping me when you are done with the min/max height thing.Would let you know.Thanks once again buddy!

**Comment by Jdruwe** [comment]
@goonerDroid How is the material design themeing going? I am very interested in this :)
