### ISSUE TITLE
drawThumbsApart

### ISSUE THREAD

**Issue by ot188183** [apptik/MultiSlider#19]
Hi

I am having two thumbs with the property set to drawThumbsApart as true and they don't overlap which is correct behaviour. 

Why do I get the same value for the both thumbs at the point where they can't overlap? I don't want to use the the stepsThumbsApart property. Can't I get the correct values just by setting the drawThumbsApart to true only?

Best regards

**Comment by djodjoni** [comment]
I am not sure I understand what you want to achieve exactly. Can you explain please.

Anyway what you have with 'drawThumbsApart' property is the expected behavior, i.e. the thumbs will never be on to of each other, but they may have the same values. This is done so that you can set value X to thumb1 and thumb2 and still be able to see the two of them.

However if you want to keep thumb1 and thumb2 apart and they can **never have the same value** then you should use 'stepsThumbsApart' property.

Simply 'drawThumbsApart' is for visual appearance, while 'stepsThumbsApart' is for the thumb values
