### ISSUE TITLE
Add new method setThumbNumber()

### ISSUE THREAD

**Issue by andgeno** [apptik/MultiSlider#24]
This method should allow to set the number of available thumbs programmatically.

**Comment by djodjoni** [comment]
nice one.  what about its behavior. what happens when:
1) you set more thumbs than already exist. how shall be the new thumbs positioned? shall we re-position the old thumbs
2) you set less thumbs than before. Then we just cut out the last ones ? Shall we re-position the others.
what do you think?

**Comment by andgeno** [comment]
Hi, thanks for your quick reply. :-)

Here's a more detailed suggestion ...

```
/** Sets the number of new thumbs. All exisitng and new thumbs on the slider
 *  will be spaced out evenly between each other if spaceOUtThumbsEvenly is
 *  set to true. Otherwise, positions of exisiting thumbs remain unchanged
 *  and new thumbs are added at the end of the slider.
 */
void setThumbNumber(int numThumbs, boolean spaceOutThumbsEvenly);

/** Sets the number of new thumbs. All existing and new thumbs are (re-)positioned
  * according to the provided positions array which must contain as many values
  * as specified by numThumbs. Otherwise, an IllegalArgumentException will be
  * thrown.
  */
void setThumbNumber(int numThumbs, int[] positions);

/** Adds a new thumb at the specified position on the slider. */
void addThumb(int position);

/** Removes the specified thumb instance from the slider. Any remaining thumbs
  * will be spaced out evenly if spaceOutThumbsEvenly is set to true. Otherise,
  * thumb positions will remain unchanged.
  */
void removeThumb(Thumb thumb, boolean spaceOutThumbsEvenly);

```

Remarks:
- I'm not sure if it's a problem if trying to put a new thumb at a position that is already occupied by another thumb.
- Maybe overload the methods setThumbNumber(int, boolean) and removeThumb(Thumb, boolean) with defaulting the booleans to true.

**Comment by djodjoni** [comment]
this seems ok for me. 
About the default behavior for setThumbNumber seems ok for me however I think the default when adding or removing thumbs by ref or position should not affect the others. meaning that for this case setThumbNumber will default to false. The reason why is that for me "setThumbNumber" is more like init stage where you expect this behavior, while adding/removing will probably be used when additional dimension needs to be included but the others values have to stay the same.

Another thing is that thumbs can stay on top of each other unless stepsThumbsApart>0 but they won't look nice unless drawThumbsApart is true. so this is why i think when adding thumbs and drawThumbsApart is false to place them on the min steps possible apart from each other (of course unless spaceOutThumbsEvenly is true) so they all be visible otherwise it would look like a bug.
