### ISSUE TITLE
multiSlider5.setMin is not setting the minimum value to the multislider

### ISSUE THREAD

**Issue by HasanShaikh** [apptik/MultiSlider#44]
I am setting the minimum and maximum values to the multislider like this,

multiSlider5 = (MultiSlider) findViewById(R.id.range_slider5);
multiSlider5.setMin(1000);
 multiSlider5.setMax(10000);

maximum value is working properly but it is not working for minimum value.

It is taking zero as minumum value after setting the minimum value as 1000

**Comment by djodjoni** [comment]
@HasanShaikh you cannot set min > max  if this is the case then you will end up with min==max set implicitly.

in order to make it work for your case you should switch the setters:
```
multiSlider5.setMax(10000);
multiSlider5.setMin(1000);
```

However this silent ignorance can be annoying and not clear as in your case. I was thinking to throw an exception if this happens. What do you think ?

**Comment by HasanShaikh** [comment]
Yes, it will be good if you rise an exception.

multiSlider5.setMax(10000);
multiSlider5.setMin(1000);

this worked for me.

**Comment by djodjoni** [comment]
ok. will be done in #45
